name: jot_it_down
description: A Flutter app for live transcription and notes.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  record: ^4.4.3
  http: ^0.13.4
  path_provider: ^2.0.11
  mime: ^1.0.1
  http_parser: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
